### ISSUE TITLE
Exception on percy.io

### ISSUE THREAD

**Issue by prymitive** [inspect-js/is-typed-array#47]
See percy/percy-storybook#194, when is-typed-array is included as a dependency it triggers an exception on percy.io:

```this engine has support for Symbol.toStringTag but BigInt64Array```

**Comment by Robdel12** [comment]
After investigating I don't believe this is related to `is-typed-array`: https://github.com/percy/percy-storybook/issues/194#issuecomment-611631338

**Comment by prymitive** [comment]
I was able to use newer chrome version on percy and that resolved the issue.

**Comment by ljharb** [comment]
I'm confused; neither `BigInt` nor `Symbol` can be polyfilled, so why would `BigInt64Array` exist, but `Symbol.toStringTag` not, even on really ol browsers?
